### ISSUE TITLE
Frontend : Production : Stake Button Stuck in Disabled State

### ISSUE THREAD

**Issue by tcouther** [yaxis-project/yaxis-frontend-v2#31]
The 'Stake' Button remains in disabled state despite input field changes. Is this intentional?
I wasn't sure it was user error, so I looked at the front-end code for bugs. 

Screenshot - https://app.yaxis.io/staking
<img width="729" alt="Screen Shot 2021-09-26 at 9 34 55 PM" src="https://user-images.githubusercontent.com/591630/134846027-63a58357-6d1f-4aaa-a400-078c700e5252.png">

Code - Here's the line of code I think causes the issue. 
https://github.com/yaxis-project/yaxis-frontend-v2/blob/78bd5abf08f97dc8140cf66edc6ef9455b11f517/src/views/Staking/components/StakingCard.tsx#L164

Observation / Suggestion
I noticed the **Unstake** button uses the "withdrawDisabled" method to determine disabled state of the button.
Can we use the same approach for the **Stake** Button, adding a similar "depositDisabled" method? 
https://github.com/yaxis-project/yaxis-frontend-v2/blob/78bd5abf08f97dc8140cf66edc6ef9455b11f517/src/views/Staking/components/StakingCard.tsx#L184

I don't have time to investigate further, but I hope this helps get staking online again.
Love the Yaxis platform!

**Comment by getgouda** [comment]
Hey @tcouther, thanks for the thorough ticket and investigation.

It unfortunately _is_ intentional.

See the various Discord threads on this: https://discord.com/channels/754774398304649308/789817386156294154/889665886481436712

It was thought this would only be for a few days, but with the audit improvements rolling through this has been pushed back. What I can do to make this more clear is add a tooltip explaining why it is disabled.

**Comment by tcouther** [comment]
> Hey @tcouther, thanks for the thorough ticket and investigation.
> 
> It unfortunately _is_ intentional.
> 
> See the various Discord threads on this: https://discord.com/channels/754774398304649308/789817386156294154/889665886481436712
> 
> It was thought this would only be for a few days, but with the audit improvements rolling through this has been pushed back. What I can do to make this more clear is add a tooltip explaining why it is disabled.

@getgouda , Thanks for the quick reply.
A tooltip would be great.
